FROM python:3.12
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
WORKDIR /db-hackathon
EXPOSE 8080
RUN ["brownie", "compile"]
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8080"]